# Generated by Django 2.2.8 on 2020-04-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpcs_user',
            name='matchDist',
            field=models.CharField(choices=[('6', '6 arcsec'), ('2', '2 arcsec'), ('1', '1 arcsec'), ('4', '4 arcsec')], default='1 arcsec', max_length=10, verbose_name='Matching radius'),
        ),
    ]
