# Generated by Django 2.2.8 on 2020-04-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200331_1755'),
        ('myapp', '0003_auto_20200401_1703'),
    ]

    operations = [
    ]
