# Generated by Django 2.2.8 on 2020-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200406_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhtomfits',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('S', 'Sended to photometry'), ('I', 'photometry in progress'), ('R', 'Result photometry'), ('F', 'Finished'), ('E', 'Error'), ('U', 'User not active')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='cpcs_user',
            name='matchDist',
            field=models.CharField(choices=[('4', '4 arcsec'), ('2', '2 arcsec'), ('1', '1 arcsec'), ('6', '6 arcsec')], default='1 arcsec', max_length=10, verbose_name='Matching radius'),
        ),
    ]
