# Generated by Django 2.2.8 on 2020-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200407_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhtomfits',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('S', 'Sended to photometry'), ('I', 'Photometry in progress'), ('R', 'Result photometry'), ('F', 'Finished'), ('E', 'Error'), ('U', 'User not active')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='cpcs_user',
            name='matchDist',
            field=models.CharField(choices=[('2', '2 arcsec'), ('4', '4 arcsec'), ('1', '1 arcsec'), ('6', '6 arcsec')], default='1 arcsec', max_length=10, verbose_name='Matching radius'),
        ),
        migrations.AlterField(
            model_name='cpcs_user',
            name='obsName',
            field=models.CharField(max_length=255, unique=True, verbose_name='Observatory name'),
        ),
    ]
