# Generated by Django 2.2.8 on 2020-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200407_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhtomfits',
            name='start_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
