# Generated by Django 2.2.8 on 2020-04-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_bhtomfits_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhtomfits',
            name='cpcs_result',
        ),
        migrations.AddField(
            model_name='bhtomfits',
            name='cpcs_plot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhtomfits',
            name='dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhtomfits',
            name='mag_err',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhtomfits',
            name='magg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhtomfits',
            name='npoints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhtomfits',
            name='outlier_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhtomfits',
            name='ra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhtomfits',
            name='scatter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bhtomfits',
            name='zeropoint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpcs_user',
            name='matchDist',
            field=models.CharField(choices=[('2', '2 arcsec'), ('4', '4 arcsec'), ('1', '1 arcsec'), ('6', '6 arcsec')], default='1 arcsec', max_length=10, verbose_name='Matching radius'),
        ),
    ]
