# Generated by Django 2.2.8 on 2020-04-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200408_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bhtomfits',
            old_name='magg',
            new_name='mag',
        ),
        migrations.AlterField(
            model_name='cpcs_user',
            name='matchDist',
            field=models.CharField(choices=[('4', '4 arcsec'), ('1', '1 arcsec'), ('6', '6 arcsec'), ('2', '2 arcsec')], default='1 arcsec', max_length=10, verbose_name='Matching radius'),
        ),
    ]
