# Generated by Django 2.2.8 on 2020-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200408_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhtomfits',
            name='ccdphot_filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cpcs_user',
            name='matchDist',
            field=models.CharField(choices=[('1', '1 arcsec'), ('4', '4 arcsec'), ('2', '2 arcsec'), ('6', '6 arcsec')], default='1 arcsec', max_length=10, verbose_name='Matching radius'),
        ),
    ]
