# Generated by Django 2.2.8 on 2020-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200409_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpcs_user',
            name='matchDist',
            field=models.CharField(choices=[('1', '1 arcsec'), ('4', '4 arcsec'), ('6', '6 arcsec'), ('2', '2 arcsec')], default='1 arcsec', max_length=10, verbose_name='Matching radius'),
        ),
        migrations.AlterField(
            model_name='cpcs_user',
            name='obsName',
            field=models.CharField(max_length=255, verbose_name='Observatory name'),
        ),
    ]
