# Generated by Django 2.2.8 on 2020-04-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20200409_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpcs_user',
            name='fits',
            field=models.FileField(default='d', upload_to='user_fits', verbose_name='Sample fits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpcs_user',
            name='matchDist',
            field=models.CharField(choices=[('4', '4 arcsec'), ('6', '6 arcsec'), ('1', '1 arcsec'), ('2', '2 arcsec')], default='1 arcsec', max_length=10, verbose_name='Matching radius'),
        ),
    ]
