LCO_APIKEY = '4afe44843de1af4bf0a6723202c110351aa13562'
SECRET_KEY= 'lhrw0-#9v8*wx8zgd^qpb99ma#klxfs3*&2$mtke!9ro4xcf)4'
ANTARES_KEY= ''
ANTARES_SECRET= ''
TWITTER_APIKEY= ''
TWITTER_SECRET= ''
TTWITTER_ACCESSTOKEN= ''
TWITTER_ACCESSTOKEN = ''
TWITTER_ACCESSSECRET= ''
TOMEMAIL= ''
TOMEMAILPASSWORD= ''
TNSBOT_APIKEY= ''
black_tom_DB_USER = 'blacktom'
black_tom_DB_PASSWORD = 'blacktom'
CPCS_DATA_ACCESS_HASHTAG= ''

CCDPHOTD_URL = 'http://localhost:8008/jobs/'
CPCS_URL = 'http://localhost:8080/cgi/'
CPCD_Admin_Hashtag = '536c008adcc19dcb6c69baf5c7b85b15'

#CCDPHOTD_URL = 'http://ccdphot.astrolabs.pl/jobs/'
#CPCS_URL = 'http://gsaweb.ast.cam.ac.uk/followup/cgi/'
#CPCD_Admin_Hashtag = ''